version: '3.3'

services:
  wechatpadpro:
    image: wechatpadpro/wechatpadpro:${WECHAT_TAG:-latest}
    container_name: wechatpadpro
    restart: always
    ports:
      - "${PORT:-1238}:1238"
    env_file:
      - .env
    environment:
      - DB_HOST=${DB_HOST}
      - REDIS_HOST=${REDIS_HOST}
      - MYSQL_CONNECT_STR=${DB_USERNAME}:${DB_PASSWORD}@tcp(${DB_HOST}:${DB_PORT})/${DB_DATABASE}?charset=utf8mb4&parseTime=true&loc=Local
    volumes:
      - ./.env:/app/.env
    networks:
      - wechatpadpro-network

networks:
  wechatpadpro-network:
    driver: bridge